# Generated by Django 5.1.3 on 2024-11-26 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в тком формате: +996XXXXXXXXX', regex='^\\+996\\d{9}$')]),
        ),
    ]
